# @package loss

objective:
  lower: 
    name: 'core.losses.LogisticDistill'
    is_lower: true
  upper:
    name: 'core.losses.LogisticDistill'
    is_lower: false
model:
  lower:
    name: 'core.models.Linear'
    n_features : 1
    n_classes : 1
    with_bias : false
    reg: 10.
    
  upper:
    name: 'core.models.ModelDataset'
    reg: 0.
