# @package loss

objective:
  lower:
    name: 'core.losses.Logistic'
    reg: true
  upper:
    name: 'core.losses.Logistic'
    reg: false
model:
  lower:
    name: 'core.models.Linear'
    n_features : 1
    n_classes : 1
    with_bias : false
    path: ''
  upper: 
    name: 'core.models.Identity'
    dim: 1
    path: ''