# @package loss

objective:
  lower:
    name: 'trainers.multitask.models.MutiTaskLoss'
    weighted: True
    apply_reg: False
    num_tasks: ${loader.num_tasks}
  upper:
    name: 'trainers.multitask.models.MutiTaskLoss'
    weighted: False
    apply_reg: True
    reg: 0.0005
    num_tasks : ${loader.num_tasks}
model:
  lower:
    name: 'trainers.multitask.models.models.MTLVGG16'
    num_tasks : ${loader.num_tasks}
    path: '' #'/home/marbel/Documents/projects/bilevel_opt_code/NonconvexBilevel/data/outputs/debug/321/torch_models/lower_model_000.pth'
  upper: 
    name: 'trainers.multitask.models.Identity'
    dim: ${loader.num_tasks}
    init: 0.1
    path: ''