name: 'BGS'
warm_start_iter : 1
unrolled_iter: 0
correction: True
add_correction: True
compute_latest_correction: True
dual_var_warm_start: True

optimizer:
  name: 'TorchOpt.sgd'
  momentum: 0.
  lr: 0.9
scheduler:
  name: 'torch.optim.lr_scheduler.CosineAnnealingLR'
  T_max: ${training.total_epoch}
  use_scheduler: False
linear_solver:
  name: 'core.linear_solvers.Normal_GD'
  lr: 0.9
  n_iter: 1
linear_op: 
  name: 'core.selection.HessianOp'
  stochastic: True
  use_new_input: True
  compute_new_grad: True