# @package selection
name : 'BGS'

optimizer:
  optimizer:
    name: 'TorchOpt.adam'
    b1: 0.9
    b2: 0.999
    eps: 0.00000001
    eps_root: 0.00000001
  scheduler:
    name: 'TorchOpt.schedule.linear_schedule'
    init_value: 0.0003
    end_value: 0.0003
    transition_steps: 1
    transition_begin: 0
  warm_start_iter : 0
  unrolled_iter: 1
linear_solver:
  algorithm:
    name: 'core.linear_solvers.SGD'
    lr: 0.00001
    n_iter: 1
  residual_op: 
    name: 'core.selection.NormalResidual'
  stochastic: True

correction: True
dual_var_warm_start: True