# @package training
outer_iterations: 100

optimizer:
  outer:
    name: 'torch.optim.SGD'
    lr : 0.01
    momentum: 0.
    nesterov: False
  inner:
    name: 'torch.optim.SGD'
    lr : 0.01
    momentum: 0.
    nesterov: False
scheduler:
  outer:
    name: 'torch.optim.lr_scheduler.CosineAnnealingLR'
    T_max: 1000
    use_scheduler: False
  inner:
    name: 'torch.optim.lr_scheduler.CosineAnnealingLR'
    T_max: 1000
    use_scheduler: False